let imageArray = [
  "images/Ari.png",
  "images/Des.png",
  "images/Lin.png",
  "images/Ethan.png",
  "images/Cjmk.png",
  // "images/Dream.png",
  // "images/Catnips.png",
  // "images/Kirby.png",
  // "images/Charmed.png",
  "images/Jules.png",
  "images/Riza.png",
  "images/Jerry.png",
  // "images/Soze.png",
  // "images/Chino.png",
  "images/Tokio.jpeg",
];
